---
# -- (Optional) When using a custom network
networks:
   teleport:
     external: true
services:
  traefik:
    image: traefik:v2.10.5
    command:
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log" 
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log" 
#      - "--entrypoints.web.address=:80"
#      - "--accesslog=true"
#      - "--accesslog.filePath=/logs/access.log"
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      # - 8889:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/:logs/
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=your-cf-api-token
    # -- (Optional) When using a custom network
    networks:
      - teleport
    restart: unless-stopped
